version: '3'
services:
  node:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27018:27017"

volumes:
  mongo-data:
